version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    #
    # volumes:
    #   - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - DB_HOST=${MYSQL_DEFAULT_HOST:-db}
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_DEFAULT_ROOT_PASSWORD:-password}
      - DB_NAME=${MYSQL_DEFAULT_DATABASE:-siriodb}
    command: ["npm", "run", "start:prod"]
    depends_on:
      - db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8090:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DEFAULT_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DEFAULT_DATABASE:-siriodb}
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "test"]
    environment:
      - NODE_ENV=test
      - DB_HOST=${MYSQL_DEFAULT_HOST:-db}
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_DEFAULT_ROOT_PASSWORD:-password}
      - DB_NAME=${MYSQL_DEFAULT_DATABASE:-siriodb}
    depends_on:
      - db

volumes:
  db:
    driver: local
